services:
  mysql:
    container_name: 'messenger_db'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=messenger'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=longquoc'
    ports:
      - '3306'
